//! Clipboard interaction and monitoring module
//! Reads and writes text, HTML, and images in-process via pure-Rust arboard
//! without spawning external CLI processes in polling loops (prevents GNOME dock shaking).

use arboard::{Clipboard, ImageData};
use std::borrow::Cow;
use std::hash::{Hash, Hasher};
use std::process::{Command, Stdio};
use std::io::Write;
use std::sync::atomic::{AtomicU64, Ordering};
use crate::backend::simulator::is_x11;
use base64::Engine;
use once_cell::sync::Lazy;
use parking_lot::Mutex;

/// Atomic registers containing the hash of the last pasted text and image.
/// The background watcher reads these to ignore events generated by our own app.
pub static LAST_TEXT_HASH: AtomicU64 = AtomicU64::new(0);
pub static LAST_IMAGE_HASH: AtomicU64 = AtomicU64::new(0);

/// Persistent global Clipboard context for reading/writing in-process
static PERSISTENT_CLIPBOARD: Lazy<Mutex<Option<Clipboard>>> = Lazy::new(|| {
    Mutex::new(Clipboard::new().ok())
});

fn command_exists(cmd: &str) -> bool {
    Command::new("which")
        .arg(cmd)
        .output()
        .map(|o| o.status.success())
        .unwrap_or(false)
}

/// Executes an operation on the persistent Clipboard context with automatic re-initialization
fn with_clipboard<F, R>(mut f: F) -> Result<R, String>
where
    F: FnMut(&mut Clipboard) -> Result<R, arboard::Error>,
{
    let mut guard = PERSISTENT_CLIPBOARD.lock();
    if guard.is_none() {
        *guard = Clipboard::new().ok();
    }
    if let Some(ref mut ctx) = *guard {
        match f(ctx) {
            Ok(val) => Ok(val),
            Err(e) => {
                if let Ok(mut fresh) = Clipboard::new() {
                    let res = f(&mut fresh);
                    *guard = Some(fresh);
                    res.map_err(|err| err.to_string())
                } else {
                    Err(e.to_string())
                }
            }
        }
    } else {
        Err("Could not initialize clipboard context".to_string())
    }
}

/// Get current text from clipboard purely in-process via arboard
/// (Does NOT spawn wl-paste/xclip subprocesses in polling loops to avoid dock flicker)
pub fn get_current_text() -> Result<String, String> {
    with_clipboard(|ctx| ctx.get_text())
}

/// Helper to write text via external command fallback
fn set_clipboard_external(cmd: &str, args: &[&str], data: &str) -> Result<(), String> {
    if !command_exists(cmd) {
        return Err(format!("Command '{}' not found", cmd));
    }

    let mut child = Command::new(cmd)
        .args(args)
        .stdin(Stdio::piped())
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .spawn()
        .map_err(|e| format!("Failed to spawn {}: {}", cmd, e))?;

    if let Some(mut stdin) = child.stdin.take() {
        stdin
            .write_all(data.as_bytes())
            .map_err(|e| format!("Pipe write error: {}", e))?;
    }

    if cmd == "xclip" || cmd == "wl-copy" {
        std::thread::spawn(move || {
            let _ = child.wait();
        });
        Ok(())
    } else {
        match child.wait() {
            Ok(status) if status.success() => Ok(()),
            Ok(status) => Err(format!("{} exited with status {}", cmd, status)),
            Err(e) => Err(format!("Process wait error: {}", e)),
        }
    }
}

/// Helper to write raw bytes (images) via external command fallback
fn set_clipboard_external_bytes(cmd: &str, args: &[&str], data: &[u8]) -> Result<(), String> {
    if !command_exists(cmd) {
        return Err(format!("Command '{}' not found", cmd));
    }

    let mut child = Command::new(cmd)
        .args(args)
        .stdin(Stdio::piped())
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .spawn()
        .map_err(|e| format!("Failed to spawn {}: {}", cmd, e))?;

    if let Some(mut stdin) = child.stdin.take() {
        stdin
            .write_all(data)
            .map_err(|e| format!("Pipe write error: {}", e))?;
    }

    if cmd == "xclip" || cmd == "wl-copy" {
        std::thread::spawn(move || {
            let _ = child.wait();
        });
        Ok(())
    } else {
        match child.wait() {
            Ok(status) if status.success() => Ok(()),
            Ok(status) => Err(format!("{} exited with status {}", cmd, status)),
            Err(e) => Err(format!("Process wait error: {}", e)),
        }
    }
}

/// Robustly set text to clipboard across Wayland, X11, and in-process
pub fn set_text_robust(text: &str) -> Result<(), String> {
    let hash = calculate_hash(text);
    LAST_TEXT_HASH.store(hash, Ordering::SeqCst);

    let mut written = false;

    // 1. If on Wayland, try wl-copy
    if !is_x11() && command_exists("wl-copy") {
        if set_clipboard_external("wl-copy", &[], text).is_ok() {
            written = true;
        }
    }

    // 2. If on X11, try xclip / xsel
    if is_x11() {
        if command_exists("xclip") {
            let _ = set_clipboard_external("xclip", &["-selection", "clipboard"], text);
            let _ = set_clipboard_external("xclip", &["-selection", "primary"], text);
            written = true;
        } else if command_exists("xsel") {
            let _ = set_clipboard_external("xsel", &["-b", "-i"], text);
            let _ = set_clipboard_external("xsel", &["-p", "-i"], text);
            written = true;
        }
    }

    // 3. In-process arboard
    if with_clipboard(|ctx| ctx.set_text(text.to_owned())).is_ok() {
        written = true;
    }

    if written {
        Ok(())
    } else {
        Err("Failed to set clipboard text".to_string())
    }
}

/// Robustly set HTML content to clipboard
pub fn set_html_robust(html: &str, plain: &str) -> Result<(), String> {
    let hash = calculate_hash(plain);
    LAST_TEXT_HASH.store(hash, Ordering::SeqCst);

    let mut written = false;

    if !is_x11() && command_exists("wl-copy") {
        let _ = set_clipboard_external("wl-copy", &["-t", "text/html"], html);
        written = true;
    }

    if is_x11() && command_exists("xclip") {
        let _ = set_clipboard_external("xclip", &["-selection", "clipboard", "-t", "text/html"], html);
        written = true;
    }

    if with_clipboard(|ctx| ctx.set_html(html.to_owned(), Some(plain.to_owned()))).is_ok() {
        written = true;
    }

    let _ = set_text_robust(plain);

    if written {
        Ok(())
    } else {
        Err("Failed to set HTML".to_string())
    }
}

/// Struct containing raw RGBA image dimensions and pixels
#[derive(Clone)]
pub struct ImageRaw {
    pub width: usize,
    pub height: usize,
    pub bytes: Vec<u8>,
}

/// Read image data from clipboard in-process
pub fn get_current_image() -> Result<Option<(ImageRaw, u64)>, String> {
    let mut ctx = match Clipboard::new() {
        Ok(c) => c,
        Err(_) => return Ok(None),
    };
    match ctx.get_image() {
        Ok(image) => {
            let bytes = image.bytes.to_vec();
            let hash = calculate_hash(&bytes);
            Ok(Some((
                ImageRaw {
                    width: image.width,
                    height: image.height,
                    bytes,
                },
                hash,
            )))
        }
        Err(_) => Ok(None),
    }
}

/// Robustly write image data to clipboard
pub fn set_image_robust(base64_str: &str, _width: u32, _height: u32) -> Result<(), String> {
    let bytes = match base64::prelude::BASE64_STANDARD.decode(base64_str) {
        Ok(b) => b,
        Err(_) => return Err("Failed to decode base64 image".to_string()),
    };

    let hash = calculate_hash(&bytes);
    LAST_IMAGE_HASH.store(hash, Ordering::SeqCst);

    let mut written = false;

    // 1. Wayland wl-copy
    if !is_x11() && command_exists("wl-copy") {
        if set_clipboard_external_bytes("wl-copy", &["-t", "image/png"], &bytes).is_ok() {
            written = true;
        }
    }

    // 2. X11 xclip
    if is_x11() && command_exists("xclip") {
        if set_clipboard_external_bytes("xclip", &["-selection", "clipboard", "-t", "image/png"], &bytes).is_ok() {
            written = true;
        }
    }

    // 3. In-process arboard
    if let Ok(img) = image::load_from_memory(&bytes) {
        let rgba = img.to_rgba8();
        let img_data = ImageData {
            width: rgba.width() as usize,
            height: rgba.height() as usize,
            bytes: Cow::Owned(rgba.into_raw()),
        };
        if with_clipboard(|ctx| ctx.set_image(img_data.clone())).is_ok() {
            written = true;
        }
    }

    if written {
        Ok(())
    } else {
        Err("Failed to write clipboard image".to_string())
    }
}

/// Converts raw RGBA pixels to a Base64-encoded PNG image
pub fn convert_image_to_base64(raw: &ImageRaw) -> Option<String> {
    let mut png_bytes = Vec::new();
    {
        let mut encoder = png::Encoder::new(&mut png_bytes, raw.width as u32, raw.height as u32);
        encoder.set_color(png::ColorType::Rgba);
        encoder.set_depth(png::BitDepth::Eight);
        let mut writer = encoder.write_header().ok()?;
        writer.write_image_data(&raw.bytes).ok()?;
    }
    Some(base64::prelude::BASE64_STANDARD.encode(png_bytes))
}

/// Calculate FNV-1a 64-bit hash
pub fn calculate_hash<T: Hash + ?Sized>(t: &T) -> u64 {
    let mut s = std::collections::hash_map::DefaultHasher::new();
    t.hash(&mut s);
    s.finish()
}

/// Public API to push extracted text into both the active OS clipboard and the SQLite history database
pub fn push_extracted_text(
    text: &str,
    db: &std::sync::Arc<parking_lot::Mutex<rusqlite::Connection>>,
) -> Result<(), String> {
    let trimmed = text.trim();
    if trimmed.is_empty() {
        return Err("Extracted text is empty".to_string());
    }

    // 1. Write to OS Clipboard
    set_text_robust(trimmed)?;

    // 2. Add item to SQLite database
    let conn = db.lock();
    let preview = if trimmed.chars().count() > 100 {
        format!("{}...", trimmed.chars().take(100).collect::<String>())
    } else {
        trimmed.to_string()
    };

    let item = crate::backend::db::ClipboardItem {
        id: uuid::Uuid::new_v4().to_string(),
        content: crate::backend::db::ClipboardContent::Text(trimmed.to_string()),
        timestamp: chrono::Utc::now(),
        pinned: false,
        preview,
    };

    if let Err(e) = crate::backend::db::insert_item(&conn, &item) {
        eprintln!("[Clipboard API] Failed to insert item into db: {}", e);
    } else {
        eprintln!("[Clipboard API] Successfully ingested {} chars into history & clipboard", trimmed.len());
    }

    Ok(())
}
