//! Clipboard interaction and monitoring module
//! Reads and writes text, HTML, and images, utilizing robust fallbacks and persistent context

use arboard::{Clipboard, ImageData};
use std::borrow::Cow;
use std::hash::{Hash, Hasher};
use std::process::{Command, Stdio};
use std::io::Write;
use std::sync::atomic::{AtomicU64, Ordering};
use crate::backend::simulator::is_x11;
use base64::Engine;
use x11rb::protocol::xproto::ConnectionExt;
use once_cell::sync::Lazy;
use parking_lot::Mutex;

/// Atomic registers containing the hash of the last pasted text and image.
/// The background watcher reads these to ignore events generated by our own app.
pub static LAST_TEXT_HASH: AtomicU64 = AtomicU64::new(0);
pub static LAST_IMAGE_HASH: AtomicU64 = AtomicU64::new(0);

/// Persistent global Clipboard context for WRITING to avoid selection loss on drop
static PERSISTENT_CLIPBOARD: Lazy<Mutex<Option<Clipboard>>> = Lazy::new(|| {
    Mutex::new(Clipboard::new().ok())
});

/// Executes a write operation on the persistent Clipboard context with automatic re-initialization on connection loss
fn with_clipboard<F, R>(mut f: F) -> Result<R, String>
where
    F: FnMut(&mut Clipboard) -> Result<R, arboard::Error>,
{
    let mut guard = PERSISTENT_CLIPBOARD.lock();
    if guard.is_none() {
        *guard = Clipboard::new().ok();
    }
    if let Some(ref mut ctx) = *guard {
        match f(ctx) {
            Ok(val) => Ok(val),
            Err(e) => {
                // If operation failed, try re-initializing connection once
                if let Ok(mut fresh) = Clipboard::new() {
                    let res = f(&mut fresh);
                    *guard = Some(fresh);
                    res.map_err(|err| err.to_string())
                } else {
                    Err(e.to_string())
                }
            }
        }
    } else {
        Err("Could not initialize clipboard context".to_string())
    }
}

/// Get current text from clipboard with command-line tools first, then fresh arboard fallback
pub fn get_current_text() -> Result<String, String> {
    if is_x11() {
        let output = Command::new("xclip")
            .args(["-selection", "clipboard", "-o"])
            .output();
        if let Ok(out) = output {
            if out.status.success() {
                let text = String::from_utf8_lossy(&out.stdout).into_owned();
                if !text.is_empty() {
                    return Ok(text);
                }
            }
        }
    } else {
        let output = Command::new("wl-paste")
            .arg("-n")
            .output();
        if let Ok(out) = output {
            if out.status.success() {
                let text = String::from_utf8_lossy(&out.stdout).into_owned();
                if !text.is_empty() {
                    return Ok(text);
                }
            }
        }
    }

    // For reading from external apps, use a fresh Clipboard instance to receive current selection notify
    let mut ctx = Clipboard::new().map_err(|e| e.to_string())?;
    ctx.get_text().map_err(|e| e.to_string())
}

/// Returns the current owner window of the CLIPBOARD selection,
/// or `None` when it cannot be determined (non-X11, connection failure).
/// `Some(0)` (x11rb::NONE) means "no owner".
pub fn clipboard_owner() -> Option<u32> {
    if !is_x11() {
        return None;
    }
    let (conn, _) = x11rb::connect(None).ok()?;
    let atom = conn
        .intern_atom(false, b"CLIPBOARD")
        .ok()?
        .reply()
        .ok()?
        .atom;
    let owner = conn.get_selection_owner(atom).ok()?.reply().ok()?.owner;
    Some(owner)
}

/// Wait (at most `budget`) for the CLIPBOARD selection owner to *change*
/// from `owner_before` (to a non-NONE owner).
pub fn settle_clipboard_handoff(owner_before: Option<u32>, budget: std::time::Duration) {
    let start = std::time::Instant::now();
    let deadline = start + budget;
    let poll_interval = std::time::Duration::from_millis(3);
    
    while std::time::Instant::now() < deadline {
        let before = match owner_before {
            Some(owner) => owner,
            None => return,
        };
        match clipboard_owner() {
            Some(owner) if owner != 0 && owner != before => return,
            _ => {}
        }
        std::thread::sleep(poll_interval);
    }
}

fn set_clipboard_external(cmd: &str, args: &[&str], data: &str) -> Result<(), String> {
    use std::io::Read;
    
    let owner_before = clipboard_owner();

    let mut child = Command::new(cmd)
        .args(args)
        .stdin(Stdio::piped())
        .stdout(Stdio::null())
        .stderr(Stdio::piped())
        .spawn()
        .map_err(|e| format!("Failed to spawn {}: {}", cmd, e))?;

    if let Some(mut stdin) = child.stdin.take() {
        stdin
            .write_all(data.as_bytes())
            .map_err(|e| format!("Pipe write error: {}", e))?;
    }

    // Wait for the helper to acquire the selection
    settle_clipboard_handoff(owner_before, std::time::Duration::from_millis(50));

    match child.try_wait() {
        Ok(Some(status)) if !status.success() => {
            let mut stderr = String::new();
            if let Some(mut stderr_pipe) = child.stderr.take() {
                let _ = stderr_pipe.read_to_string(&mut stderr);
            }
            Err(format!(
                "{} exited with status {}. Stderr: {}",
                cmd,
                status,
                stderr.trim()
            ))
        }
        Ok(_) => {
            if cmd == "xclip" {
                std::thread::spawn(move || {
                    let _ = child.wait();
                });
            }
            Ok(())
        }
        Err(e) => Err(format!("Process status check failed: {}", e)),
    }
}

fn set_clipboard_external_bytes(cmd: &str, args: &[&str], data: &[u8]) -> Result<(), String> {
    use std::io::Read;
    
    let owner_before = clipboard_owner();

    let mut child = Command::new(cmd)
        .args(args)
        .stdin(Stdio::piped())
        .stdout(Stdio::null())
        .stderr(Stdio::piped())
        .spawn()
        .map_err(|e| format!("Failed to spawn {}: {}", cmd, e))?;

    if let Some(mut stdin) = child.stdin.take() {
        stdin
            .write_all(data)
            .map_err(|e| format!("Pipe write error: {}", e))?;
    }

    // Wait for the helper to acquire the selection
    settle_clipboard_handoff(owner_before, std::time::Duration::from_millis(50));

    match child.try_wait() {
        Ok(Some(status)) if !status.success() => {
            let mut stderr = String::new();
            if let Some(mut stderr_pipe) = child.stderr.take() {
                let _ = stderr_pipe.read_to_string(&mut stderr);
            }
            Err(format!(
                "{} exited with status {}. Stderr: {}",
                cmd,
                status,
                stderr.trim()
            ))
        }
        Ok(_) => {
            if cmd == "xclip" {
                std::thread::spawn(move || {
                    let _ = child.wait();
                });
            }
            Ok(())
        }
        Err(e) => Err(format!("Process status check failed: {}", e)),
    }
}

/// Robustly set text to clipboard
pub fn set_text_robust(text: &str) -> Result<(), String> {
    let hash = calculate_hash(text);
    LAST_TEXT_HASH.store(hash, Ordering::SeqCst);

    // Prefer external utilities on Linux to avoid losing selection on drop
    if !is_x11() {
        if set_clipboard_external(
            "wl-copy",
            &["--type", "text/plain;charset=utf-8"],
            text,
        ).is_ok() {
            return Ok(());
        }
    } else {
        if set_clipboard_external(
            "xclip",
            &["-selection", "clipboard", "-t", "UTF8_STRING"],
            text,
        ).is_ok() {
            return Ok(());
        }
    }

    // Fallback to persistent arboard context
    with_clipboard(|ctx| ctx.set_text(text.to_owned()))
}

/// Robustly set HTML content to clipboard
pub fn set_html_robust(html: &str, plain: &str) -> Result<(), String> {
    let hash = calculate_hash(plain);
    LAST_TEXT_HASH.store(hash, Ordering::SeqCst);

    // Prefer external utilities on Linux to avoid losing selection on drop
    let mut set_external_success = false;
    if !is_x11() {
        if set_clipboard_external("wl-copy", &["--type", "text/html"], html).is_ok() {
            let _ = set_text_robust(plain);
            set_external_success = true;
        }
    } else {
        if set_clipboard_external(
            "xclip",
            &["-selection", "clipboard", "-t", "text/html"],
            html,
        ).is_ok() {
            let _ = set_text_robust(plain);
            set_external_success = true;
        }
    }

    if set_external_success {
        return Ok(());
    }

    // Fallback to persistent arboard context
    with_clipboard(|ctx| ctx.set_html(html.to_owned(), Some(plain.to_owned())))
}

/// Struct containing raw RGBA image dimensions and pixels
#[derive(Clone)]
pub struct ImageRaw {
    pub width: usize,
    pub height: usize,
    pub bytes: Vec<u8>,
}

/// Read image data from clipboard
pub fn get_current_image() -> Result<Option<(ImageRaw, u64)>, String> {
    let mut ctx = match Clipboard::new() {
        Ok(c) => c,
        Err(_) => return Ok(None),
    };
    match ctx.get_image() {
        Ok(image) => {
            let bytes = image.bytes.to_vec();
            let hash = calculate_hash(&bytes);
            Ok(Some((
                ImageRaw {
                    width: image.width,
                    height: image.height,
                    bytes,
                },
                hash,
            )))
        }
        Err(_) => Ok(None),
    }
}

/// Robustly write image data to clipboard
pub fn set_image_robust(base64_str: &str, _width: u32, _height: u32) -> Result<(), String> {
    let bytes = match base64::prelude::BASE64_STANDARD.decode(base64_str) {
        Ok(b) => b,
        Err(_) => return Err("Failed to decode base64 image".to_string()),
    };

    let hash = calculate_hash(&bytes);
    LAST_IMAGE_HASH.store(hash, Ordering::SeqCst);

    // Prefer external utilities on Linux to avoid losing selection on drop
    let mut set_external_success = false;
    if !is_x11() {
        if set_clipboard_external_bytes("wl-copy", &["--type", "image/png"], &bytes).is_ok() {
            set_external_success = true;
        }
    } else {
        if set_clipboard_external_bytes(
            "xclip",
            &["-selection", "clipboard", "-t", "image/png"],
            &bytes,
        ).is_ok() {
            set_external_success = true;
        }
    }

    if set_external_success {
        return Ok(());
    }

    // Fallback to persistent arboard context
    let img = image::load_from_memory(&bytes).map_err(|e| e.to_string())?;
    let rgba = img.to_rgba8();

    let img_data = ImageData {
        width: rgba.width() as usize,
        height: rgba.height() as usize,
        bytes: Cow::Owned(rgba.into_raw()),
    };

    with_clipboard(|ctx| ctx.set_image(img_data.clone()))
}

/// Converts raw RGBA pixels to a Base64-encoded PNG image
pub fn convert_image_to_base64(raw: &ImageRaw) -> Option<String> {
    let mut png_bytes = Vec::new();
    {
        let mut encoder = png::Encoder::new(&mut png_bytes, raw.width as u32, raw.height as u32);
        encoder.set_color(png::ColorType::Rgba);
        encoder.set_depth(png::BitDepth::Eight);
        let mut writer = encoder.write_header().ok()?;
        writer.write_image_data(&raw.bytes).ok()?;
    }
    Some(base64::prelude::BASE64_STANDARD.encode(png_bytes))
}

/// Calculate FNV-1a 64-bit hash
pub fn calculate_hash<T: Hash + ?Sized>(t: &T) -> u64 {
    let mut s = std::collections::hash_map::DefaultHasher::new();
    t.hash(&mut s);
    s.finish()
}

/// Public API to push extracted text (e.g. from OCR or external modules)
/// into both the active OS clipboard and the SQLite history database.
pub fn push_extracted_text(
    text: &str,
    db: &std::sync::Arc<parking_lot::Mutex<rusqlite::Connection>>,
) -> Result<(), String> {
    let trimmed = text.trim();
    if trimmed.is_empty() {
        return Err("Extracted text is empty".to_string());
    }

    // 1. Write to OS Clipboard
    set_text_robust(trimmed)?;

    // 2. Add item to SQLite database
    let conn = db.lock();
    let preview = if trimmed.len() > 100 {
        format!("{}...", &trimmed[..100])
    } else {
        trimmed.to_string()
    };

    let item = crate::backend::db::ClipboardItem {
        id: uuid::Uuid::new_v4().to_string(),
        content: crate::backend::db::ClipboardContent::Text(trimmed.to_string()),
        timestamp: chrono::Utc::now(),
        pinned: false,
        preview,
    };

    if let Err(e) = crate::backend::db::insert_item(&conn, &item) {
        eprintln!("[Clipboard API] Failed to insert item into db: {}", e);
    } else {
        eprintln!("[Clipboard API] Successfully ingested {} chars into history & clipboard", trimmed.len());
    }

    Ok(())
}
